### ISSUE TITLE
link Discord

### ISSUE THREAD

**Issue by Valdior** [We-Are-Swissborg/WASB-Front#22]
Pour devenir membre, y'a un problème au niveau de la saisie Discord.

![Image](https://github.com/We-Are-Swissborg/WASB-Front/assets/4605318/73130292-c43f-4faa-8c7e-203c126b67dd)

**Comment by KeotiseuF** [comment]
C'est normal on utilise les nouvelles normes Discord : https://support.discord.com/hc/en-us/articles/12620128861463-New-Usernames-Display-Names
