### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by Valdior** [We-Are-Swissborg/WASB-Front#5]

**Comment by KeotiseuF** [comment]
What is this page supposed to contain ?

**Comment by Valdior** [comment]
Hello, cela fait 5 semaines que le ticket t'es assignée.
Où en es-tu ? Tu bloques quelques part ?

**Comment by KeotiseuF** [comment]
Suite au changement que t'avais fait, tu m'avais conseillé de tout refaire mais je t'avais dit que j'allais tout regroupé sur la même branch ce que j'ai fait dans ma dernière PR (9 redirect after logout). Du coup tu peux close cette issue.

**Comment by Valdior** [comment]
D'accord, tu as bien refait une partie du Profil utilisateur.
Mais ce n'est pas terminé, il n'y a actuellement aucun moyen de modifier les changements du profil

**Comment by Valdior** [comment]
Un petit ajout, si pas trop tard.
Est-ce que tu pourrais mettre en place un champ avec le code de parrainage ? 
Se serait quelque chose du style 'https://hostname/users/coderef/XX00X' que tu as mis en place :)

Ainsi on pourrait facilement le copier/coller à un ami :D
